language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - TOXENV=py

install:
  - pip install tox coveralls

script:
  - make test

after_success:
  - tox -e cover
  - coveralls
